modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the the FML version. This is currently 47.
loaderVersion="[${loader_version},)" #mandatory
license="${mod_license}"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    authors="${mod_authors}" #optional
    description='''${mod_description}'''
    logoFile = "icon.png"
    displayURL = "${mod_url}"

[[mixins]]
    config="${mod_id}.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[21.0.0-alpha,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="kubejs"
    type="optional"
    versionRange="[2100.7.0-build.56,)"
    ordering="NONE"
    side="BOTH"
    [dependencies."${mod_id}".mc-publish]
        modrinth="kubejs(optional)"
        curseforge="kubejs(optional)"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features."${mod_id}"]
#openGLVersion="[3.2,)"

[mc-publish]
    modrinth="4j9t5fYZ"
    curseforge=1062227
    loaders=["neoforge"]